<!doctype html>
<html lang="fr">
<head>
    <meta charset="UTF-8">
    <title>Blog</title>
    <link rel="stylesheet" href="<?=$wwwUrl?>/css/Stylesheet.css">
    <link rel="stylesheet" href="<?=$wwwUrl?>/css/themes/<?=$stylesheet?>">
    <link href='http://fonts.googleapis.com/css?family=Playfair+Display' rel='stylesheet' type='text/css'>
    <link rel="icon" type="image/png" href="<?=$wwwUrl?>/images/One-Piece-anime.png">
    <script src="http://cdnjs.cloudflare.com/ajax/libs/jquery/2.1.1/jquery.js"></script>
</head>

<body>
    <h1><a href="<?=$wwwUrl?>"><?=$blogTitle?></a></h1>
    <?php include $template ?>

    <footer class="blog-footer">

    </footer>
    <script src="<?=$wwwUrl?>/js/blog.js"></script>
</body>
</html>
